<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class Seeder000005WebMenu extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $data = [
            [
                'web_menu_id' => 1,
                'fk_web_menu_global' => 1,
                'fk_m_hak_akses' => 1,
                'wm_parent_id' => null,
                'wm_urutan_menu' => 3,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 2,
                'fk_web_menu_global' => 2,
                'fk_m_hak_akses' => 1,
                'wm_parent_id' => 1,
                'wm_urutan_menu' => 1,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 3,
                'fk_web_menu_global' => 3,
                'fk_m_hak_akses' => 1,
                'wm_parent_id' => 1,
                'wm_urutan_menu' => 2,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            // SKIP ID 4-72: Tidak ada di data SQL
            [
                'web_menu_id' => 73,
                'fk_web_menu_global' => 1,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => null,
                'wm_urutan_menu' => 6,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 74,
                'fk_web_menu_global' => 2,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 73,
                'wm_urutan_menu' => 10,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 75,
                'fk_web_menu_global' => 3,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 73,
                'wm_urutan_menu' => 11,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 76,
                'fk_web_menu_global' => 61,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 73,
                'wm_urutan_menu' => 12,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 77,
                'fk_web_menu_global' => 65,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 73,
                'wm_urutan_menu' => 13,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 78,
                'fk_web_menu_global' => 66,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 73,
                'wm_urutan_menu' => 14,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 79,
                'fk_web_menu_global' => 15,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => null,
                'wm_urutan_menu' => 5,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 80,
                'fk_web_menu_global' => 16,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 79,
                'wm_urutan_menu' => 6,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 81,
                'fk_web_menu_global' => 17,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 79,
                'wm_urutan_menu' => 7,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            // SKIP ID 82: isDeleted = 1
            [
                'web_menu_id' => 83,
                'fk_web_menu_global' => 19,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 79,
                'wm_urutan_menu' => 9,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 84,
                'fk_web_menu_global' => 20,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 79,
                'wm_urutan_menu' => 10,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 85,
                'fk_web_menu_global' => 27,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => null,
                'wm_urutan_menu' => 7,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 86,
                'fk_web_menu_global' => 28,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 85,
                'wm_urutan_menu' => 7,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 87,
                'fk_web_menu_global' => 29,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 85,
                'wm_urutan_menu' => 8,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 88,
                'fk_web_menu_global' => 30,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 85,
                'wm_urutan_menu' => 9,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 89,
                'fk_web_menu_global' => 31,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => null,
                'wm_urutan_menu' => 8,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 90,
                'fk_web_menu_global' => 32,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 89,
                'wm_urutan_menu' => 5,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 91,
                'fk_web_menu_global' => 33,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 89,
                'wm_urutan_menu' => 6,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 92,
                'fk_web_menu_global' => 34,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => null,
                'wm_urutan_menu' => 9,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 93,
                'fk_web_menu_global' => 35,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 92,
                'wm_urutan_menu' => 9,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 94,
                'fk_web_menu_global' => 36,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 92,
                'wm_urutan_menu' => 10,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 95,
                'fk_web_menu_global' => 37,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 92,
                'wm_urutan_menu' => 11,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 96,
                'fk_web_menu_global' => 57,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 92,
                'wm_urutan_menu' => 12,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 97,
                'fk_web_menu_global' => 38,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => null,
                'wm_urutan_menu' => 10,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 98,
                'fk_web_menu_global' => 39,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 97,
                'wm_urutan_menu' => 5,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 99,
                'fk_web_menu_global' => 40,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 97,
                'wm_urutan_menu' => 6,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 100,
                'fk_web_menu_global' => 41,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => null,
                'wm_urutan_menu' => 11,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 101,
                'fk_web_menu_global' => 42,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 100,
                'wm_urutan_menu' => 5,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 102,
                'fk_web_menu_global' => 43,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 100,
                'wm_urutan_menu' => 6,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 103,
                'fk_web_menu_global' => 44,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => null,
                'wm_urutan_menu' => 12,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 104,
                'fk_web_menu_global' => 45,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 103,
                'wm_urutan_menu' => 5,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 105,
                'fk_web_menu_global' => 46,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 103,
                'wm_urutan_menu' => 6,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 106,
                'fk_web_menu_global' => 47,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => null,
                'wm_urutan_menu' => 13,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 107,
                'fk_web_menu_global' => 48,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 106,
                'wm_urutan_menu' => 7,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 108,
                'fk_web_menu_global' => 49,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 106,
                'wm_urutan_menu' => 8,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 109,
                'fk_web_menu_global' => 50,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 106,
                'wm_urutan_menu' => 9,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 110,
                'fk_web_menu_global' => 51,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => null,
                'wm_urutan_menu' => 14,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 111,
                'fk_web_menu_global' => 52,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 110,
                'wm_urutan_menu' => 13,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 112,
                'fk_web_menu_global' => 53,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 110,
                'wm_urutan_menu' => 14,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 113,
                'fk_web_menu_global' => 54,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 110,
                'wm_urutan_menu' => 15,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 114,
                'fk_web_menu_global' => 55,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 110,
                'wm_urutan_menu' => 16,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 115,
                'fk_web_menu_global' => 56,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 110,
                'wm_urutan_menu' => 17,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 116,
                'fk_web_menu_global' => 58,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => null,
                'wm_urutan_menu' => 15,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 117,
                'fk_web_menu_global' => 59,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 116,
                'wm_urutan_menu' => 5,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 118,
                'fk_web_menu_global' => 60,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 116,
                'wm_urutan_menu' => 6,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 119,
                'fk_web_menu_global' => 62,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => null,
                'wm_urutan_menu' => 16,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 120,
                'fk_web_menu_global' => 63,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 119,
                'wm_urutan_menu' => 5,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 121,
                'fk_web_menu_global' => 64,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 119,
                'wm_urutan_menu' => 6,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 122,
                'fk_web_menu_global' => 27,
                'fk_m_hak_akses' => 4,
                'wm_parent_id' => null,
                'wm_urutan_menu' => 1,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 123,
                'fk_web_menu_global' => 28,
                'fk_m_hak_akses' => 4,
                'wm_parent_id' => 122,
                'wm_urutan_menu' => 1,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 124,
                'fk_web_menu_global' => 29,
                'fk_m_hak_akses' => 4,
                'wm_parent_id' => 122,
                'wm_urutan_menu' => 2,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 125,
                'fk_web_menu_global' => 30,
                'fk_m_hak_akses' => 4,
                'wm_parent_id' => 122,
                'wm_urutan_menu' => 3,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 126,
                'fk_web_menu_global' => 5,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => null,
                'wm_urutan_menu' => 4,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 127,
                'fk_web_menu_global' => 6,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 126,
                'wm_urutan_menu' => 1,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            // SKIP ID 128: isDeleted = 1
            [
                'web_menu_id' => 129,
                'fk_web_menu_global' => 76,
                'fk_m_hak_akses' => 1,
                'wm_parent_id' => null,
                'wm_urutan_menu' => 2,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 130,
                'fk_web_menu_global' => 61,
                'fk_m_hak_akses' => 1,
                'wm_parent_id' => 1,
                'wm_urutan_menu' => 3,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 131,
                'fk_web_menu_global' => 65,
                'fk_m_hak_akses' => 1,
                'wm_parent_id' => 1,
                'wm_urutan_menu' => 4,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 132,
                'fk_web_menu_global' => 66,
                'fk_m_hak_akses' => 1,
                'wm_parent_id' => 1,
                'wm_urutan_menu' => 5,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            // SKIP ID 133: isDeleted = 1
            [
                'web_menu_id' => 134,
                'fk_web_menu_global' => 78,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => null,
                'wm_urutan_menu' => 17,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 135,
                'fk_web_menu_global' => 79,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 134,
                'wm_urutan_menu' => 11,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 136,
                'fk_web_menu_global' => 80,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 134,
                'wm_urutan_menu' => 12,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 137,
                'fk_web_menu_global' => 81,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 134,
                'wm_urutan_menu' => 13,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 138,
                'fk_web_menu_global' => 83,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 134,
                'wm_urutan_menu' => 9,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 139,
                'fk_web_menu_global' => 84,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 134,
                'wm_urutan_menu' => 14,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 140,
                'fk_web_menu_global' => 21,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 79,
                'wm_urutan_menu' => 11,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 141,
                'fk_web_menu_global' => 22,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => 79,
                'wm_urutan_menu' => 12,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 142,
                'fk_web_menu_global' => 62,
                'fk_m_hak_akses' => 4,
                'wm_parent_id' => null,
                'wm_urutan_menu' => 2,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 143,
                'fk_web_menu_global' => 63,
                'fk_m_hak_akses' => 4,
                'wm_parent_id' => 142,
                'wm_urutan_menu' => 1,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 144,
                'fk_web_menu_global' => 62,
                'fk_m_hak_akses' => 3,
                'wm_parent_id' => null,
                'wm_urutan_menu' => 1,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 145,
                'fk_web_menu_global' => 64,
                'fk_m_hak_akses' => 3,
                'wm_parent_id' => 144,
                'wm_urutan_menu' => 1,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 146,
                'fk_web_menu_global' => 4,
                'fk_m_hak_akses' => 5,
                'wm_parent_id' => null,
                'wm_urutan_menu' => 1,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 147,
                'fk_web_menu_global' => 5,
                'fk_m_hak_akses' => 5,
                'wm_parent_id' => null,
                'wm_urutan_menu' => 2,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 148,
                'fk_web_menu_global' => 6,
                'fk_m_hak_akses' => 5,
                'wm_parent_id' => 147,
                'wm_urutan_menu' => 1,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 149,
                'fk_web_menu_global' => 7,
                'fk_m_hak_akses' => 5,
                'wm_parent_id' => 147,
                'wm_urutan_menu' => 2,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 150,
                'fk_web_menu_global' => 8,
                'fk_m_hak_akses' => 5,
                'wm_parent_id' => 147,
                'wm_urutan_menu' => 3,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 151,
                'fk_web_menu_global' => 9,
                'fk_m_hak_akses' => 5,
                'wm_parent_id' => null,
                'wm_urutan_menu' => 3,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 152,
                'fk_web_menu_global' => 10,
                'fk_m_hak_akses' => 5,
                'wm_parent_id' => 151,
                'wm_urutan_menu' => 1,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 153,
                'fk_web_menu_global' => 11,
                'fk_m_hak_akses' => 5,
                'wm_parent_id' => 151,
                'wm_urutan_menu' => 2,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 154,
                'fk_web_menu_global' => 12,
                'fk_m_hak_akses' => 5,
                'wm_parent_id' => 151,
                'wm_urutan_menu' => 3,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 155,
                'fk_web_menu_global' => 13,
                'fk_m_hak_akses' => 5,
                'wm_parent_id' => 151,
                'wm_urutan_menu' => 4,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 156,
                'fk_web_menu_global' => 14,
                'fk_m_hak_akses' => 5,
                'wm_parent_id' => 151,
                'wm_urutan_menu' => 5,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 157,
                'fk_web_menu_global' => 15,
                'fk_m_hak_akses' => 5,
                'wm_parent_id' => null,
                'wm_urutan_menu' => 4,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 158,
                'fk_web_menu_global' => 16,
                'fk_m_hak_akses' => 5,
                'wm_parent_id' => 157,
                'wm_urutan_menu' => 1,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 159,
                'fk_web_menu_global' => 17,
                'fk_m_hak_akses' => 5,
                'wm_parent_id' => 157,
                'wm_urutan_menu' => 2,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 160,
                'fk_web_menu_global' => 18,
                'fk_m_hak_akses' => 5,
                'wm_parent_id' => 157,
                'wm_urutan_menu' => 3,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 161,
                'fk_web_menu_global' => 19,
                'fk_m_hak_akses' => 5,
                'wm_parent_id' => 157,
                'wm_urutan_menu' => 4,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 162,
                'fk_web_menu_global' => 20,
                'fk_m_hak_akses' => 5,
                'wm_parent_id' => 157,
                'wm_urutan_menu' => 5,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 163,
                'fk_web_menu_global' => 21,
                'fk_m_hak_akses' => 5,
                'wm_parent_id' => 157,
                'wm_urutan_menu' => 6,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 164,
                'fk_web_menu_global' => 22,
                'fk_m_hak_akses' => 5,
                'wm_parent_id' => 157,
                'wm_urutan_menu' => 7,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 165,
                'fk_web_menu_global' => 23,
                'fk_m_hak_akses' => 5,
                'wm_parent_id' => null,
                'wm_urutan_menu' => 5,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 166,
                'fk_web_menu_global' => 24,
                'fk_m_hak_akses' => 5,
                'wm_parent_id' => 165,
                'wm_urutan_menu' => 1,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 167,
                'fk_web_menu_global' => 25,
                'fk_m_hak_akses' => 5,
                'wm_parent_id' => 165,
                'wm_urutan_menu' => 2,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 168,
                'fk_web_menu_global' => 26,
                'fk_m_hak_akses' => 5,
                'wm_parent_id' => 165,
                'wm_urutan_menu' => 3,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 169,
                'fk_web_menu_global' => 23,
                'fk_m_hak_akses' => 7,
                'wm_parent_id' => null,
                'wm_urutan_menu' => 1,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 170,
                'fk_web_menu_global' => 24,
                'fk_m_hak_akses' => 7,
                'wm_parent_id' => 169,
                'wm_urutan_menu' => 1,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 171,
                'fk_web_menu_global' => 25,
                'fk_m_hak_akses' => 7,
                'wm_parent_id' => 169,
                'wm_urutan_menu' => 2,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 172,
                'fk_web_menu_global' => 26,
                'fk_m_hak_akses' => 7,
                'wm_parent_id' => 169,
                'wm_urutan_menu' => 3,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 173,
                'fk_web_menu_global' => 27,
                'fk_m_hak_akses' => 7,
                'wm_parent_id' => null,
                'wm_urutan_menu' => 2,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 174,
                'fk_web_menu_global' => 28,
                'fk_m_hak_akses' => 7,
                'wm_parent_id' => 173,
                'wm_urutan_menu' => 1,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 175,
                'fk_web_menu_global' => 29,
                'fk_m_hak_akses' => 7,
                'wm_parent_id' => 173,
                'wm_urutan_menu' => 2,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 176,
                'fk_web_menu_global' => 30,
                'fk_m_hak_akses' => 7,
                'wm_parent_id' => 173,
                'wm_urutan_menu' => 3,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 177,
                'fk_web_menu_global' => 31,
                'fk_m_hak_akses' => 7,
                'wm_parent_id' => null,
                'wm_urutan_menu' => 3,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 178,
                'fk_web_menu_global' => 32,
                'fk_m_hak_akses' => 7,
                'wm_parent_id' => 177,
                'wm_urutan_menu' => 1,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 179,
                'fk_web_menu_global' => 33,
                'fk_m_hak_akses' => 7,
                'wm_parent_id' => 177,
                'wm_urutan_menu' => 2,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 180,
                'fk_web_menu_global' => 87,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => null,
                'wm_urutan_menu' => 18,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_id' => 181,
                'fk_web_menu_global' => 88,
                'fk_m_hak_akses' => 2,
                'wm_parent_id' => null,
                'wm_urutan_menu' => 19,
                'wm_menu_nama' => null,
                'wm_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
        ];

        DB::table('web_menu')->insertOrIgnore($data);
    }
}
