<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class Seeder000003WebMenuUrl extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $data = [
            [
                'web_menu_url_id' => 1,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'menu-management',
                'controller_name' => 'AdminWeb\\MenuManagement\\MenuManagementController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'untuk melakukan pengaturan akses menu',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 2,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'management-level',
                'controller_name' => 'ManagePengguna\\HakAksesController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'untuk melakukan pengaturan akses level',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 3,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'beranda',
                'controller_name' => 'SistemInformasi\\Beranda\\BerandaController',
                'module_type' => 'user',
                'wmu_keterangan' => 'Ini adalah menu beranda',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 4,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'profile-ppid',
                'controller_name' => 'SistemInformasi\\Profile\\ProfilePPIDController',
                'module_type' => 'user',
                'wmu_keterangan' => 'ini adalah menu Profile PPID',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 5,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'profile-polinema',
                'controller_name' => 'SistemInformasi\\Profile\\ProfilePolinemaController',
                'module_type' => 'user',
                'wmu_keterangan' => 'ini adalah Profil Polinema',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 6,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'struktur-organisasi',
                'controller_name' => 'SistemInformasi\\StrukturOrganisasi\\StrukturOrganisasiController',
                'module_type' => 'user',
                'wmu_keterangan' => 'ini adalah menu struktur organisasi',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 7,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'permohonan-informasi',
                'controller_name' => 'SistemInformasi\\DaftarPengajuan\\PermohonanInformasiController',
                'module_type' => 'user',
                'wmu_keterangan' => 'ini menu permohonan informasi',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 8,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'pernyataan-keberatan',
                'controller_name' => 'SistemInformasi\\DaftarPengajuan\\PernyataanKeberatanController',
                'module_type' => 'user',
                'wmu_keterangan' => 'ini adalah menu pernyatanan keberatan',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 9,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'pengaduan-masyarakat',
                'controller_name' => 'SistemInformasi\\DaftarPengajuan\\PengaduanMasyarakatController',
                'module_type' => 'user',
                'wmu_keterangan' => 'ini adalah menu pengaduan masyarakat',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 10,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'whistle-blowing-system',
                'controller_name' => 'SistemInformasi\\DaftarPengajuan\\WhistleBlowingSystemController',
                'module_type' => 'user',
                'wmu_keterangan' => 'ini adalah menu WBS',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 11,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'permohonan-sarana-dan-prasarana',
                'controller_name' => 'SistemInformasi\\DaftarPengajuan\\PermohonanSarprasController',
                'module_type' => 'user',
                'wmu_keterangan' => 'ini adalah menu sarpras',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 12,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'regulasi',
                'controller_name' => 'SistemInformasi\\Regulasi\\RegulasiController',
                'module_type' => 'user',
                'wmu_keterangan' => 'ini adalah menu regulasi',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 13,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'daftar-informasi-publik',
                'controller_name' => 'SistemInformasi\\InformasiPublik\\DaftarInformasiPublikController',
                'module_type' => 'user',
                'wmu_keterangan' => 'ini adalah menu untuk Daftar Informasi Publik',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 14,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'informasi-berkala',
                'controller_name' => 'SistemInformasi\\InformasiPublik\\InformasiBerkalaController',
                'module_type' => 'user',
                'wmu_keterangan' => 'ini adalah menu untuk informasi berkala',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 15,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'informasi-setiap-saat',
                'controller_name' => 'SistemInformasi\\InformasiPublik\\InformasiSetiapSaatController',
                'module_type' => 'user',
                'wmu_keterangan' => 'ini adalah menu untuk informasi setiap saat',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 16,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'informasi-serta-merta',
                'controller_name' => 'SistemInformasi\\InformasiPublik\\InformasiSertaMertaController',
                'module_type' => 'user',
                'wmu_keterangan' => 'ini adalah menu untuk informasi serta merta',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 17,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'informasi-dikecualikan',
                'controller_name' => 'SistemInformasi\\InformasiPublik\\InformasiDikecualikanController',
                'module_type' => 'user',
                'wmu_keterangan' => 'ini adalah menu untuk informasi dikecualikan',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 18,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'lhkpn',
                'controller_name' => 'SistemInformasi\\InformasiPublik\\LHKPN\\LHKPNController',
                'module_type' => 'user',
                'wmu_keterangan' => 'ini adalah menu lhkpn',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 19,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'pedoman-umum-pengelolaan-layanan',
                'controller_name' => 'SistemInformasi\\Pedoman\\PedomanUmumController',
                'module_type' => 'user',
                'wmu_keterangan' => 'ini adalah menu untuk pedoman umum pengelolaan layanan',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 20,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'pedoman-layanan-kerjasama',
                'controller_name' => 'SistemInformasi\\Pedoman\\PedomanKerjasamaController',
                'module_type' => 'user',
                'wmu_keterangan' => 'ini adalah menu untuk pedoman layanan kerjasama',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 21,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'prosedur-layanan-informasi',
                'controller_name' => 'SistemInformasi\\Pedoman\\ProsedurLayananController',
                'module_type' => 'user',
                'wmu_keterangan' => 'ini adalah menu untuk melihat prosedur layanan informasi',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 22,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'kategori-form',
                'controller_name' => 'SistemInformasi\\KategoriForm\\KategoriFormController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'ini adalah menu kategori form',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 23,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'timeline',
                'controller_name' => 'SistemInformasi\\Timeline\\TimelineController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'ini adalah menu untuk Timeline',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 24,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'ketentuan-pelaporan',
                'controller_name' => 'SistemInformasi\\KetentuanPelaporan\\KetentuanPelaporanController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'ini adalah menu untuk ketentuan pelaporan',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 25,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'kategori-footer',
                'controller_name' => 'AdminWeb\\Footer\\KategoriFooterController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'ini adalah menu kategori footer',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 26,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'detail-footer',
                'controller_name' => 'AdminWeb\\Footer\\FooterController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'ini adalah menu untuk footer',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 27,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'kategori-akses-cepat',
                'controller_name' => 'AdminWeb\\KategoriAkses\\KategoriAksesController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'ini adalah menu untuk kategori akses',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 28,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'detail-akses-cepat',
                'controller_name' => 'AdminWeb\\KategoriAkses\\AksesCepatController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'ini adalah menu untuk akses cepat',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 29,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'kategori-pintasan-lainnya',
                'controller_name' => 'AdminWeb\\KategoriAkses\\PintasanLainnyaController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'ini adalah menu katrgori Pintasan Lainnya',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 30,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'kategori-berita',
                'controller_name' => 'AdminWeb\\Berita\\BeritaDinamisController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'ini adalah menu untuk kategori berita',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 31,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'detail-berita',
                'controller_name' => 'AdminWeb\\Berita\\BeritaController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'ini adalah menu untuk berita',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 32,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'kategori-pengumuman',
                'controller_name' => 'AdminWeb\\Pengumuman\\PengumumanDinamisController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'ini adalah menu untuk kategori pengumuman',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 33,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'detail-pengumuman',
                'controller_name' => 'AdminWeb\\Pengumuman\\PengumumanController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'ini adalah menu untuk pengumuman',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 34,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'kategori-tahun-lhkpn',
                'controller_name' => 'AdminWeb\\InformasiPublik\\LHKPN\\LhkpnController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'ini adalah menu untuk tahun lhkpn',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 35,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'detail-lhkpn',
                'controller_name' => 'AdminWeb\\InformasiPublik\\LHKPN\\DetailLhkpnController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'ini adalah menu untuk detail lhkpn',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 36,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'kategori-regulasi',
                'controller_name' => 'AdminWeb\\InformasiPublik\\Regulasi\\KategoriRegulasiController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'ini adalah menu untuk kategori regulasi',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 37,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'regulasi-dinamis',
                'controller_name' => 'AdminWeb\\InformasiPublik\\Regulasi\\RegulasiDinamisController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'ini adalah menu untuk regulasi dinamis',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 38,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'detail-regulasi',
                'controller_name' => 'AdminWeb\\InformasiPublik\\Regulasi\\RegulasiController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'ini adalah menu untuk regulasi',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 39,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'permohonan-informasi-admin',
                'controller_name' => 'SistemInformasi\\EForm\\PermohonanInformasiController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'ini menu permohonan informasi bagian admin',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 40,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'pernyataan-keberatan-admin',
                'controller_name' => 'SistemInformasi\\EForm\\PernyataanKeberatanController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'ini adalah menu pernyataan keberatan bagian admin',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 41,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'pengaduan-masyarakat-admin',
                'controller_name' => 'SistemInformasi\\EForm\\PengaduanMasyarakatController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'ini adalah menu pengaduan masyarakat bagian admin',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 42,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'whistle-blowing-system-admin',
                'controller_name' => 'SistemInformasi\\EForm\\WBSController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'ini adalah menu WBS bagian admin',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 43,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'permohonan-sarana-dan-prasarana-admin',
                'controller_name' => 'SistemInformasi\\EForm\\PermohonanPerawatanController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'ini adalah menu sarpras bagian admin',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 44,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'detail-pintasan-lainnya',
                'controller_name' => 'AdminWeb\\KategoriAkses\\DetailPintasanLainnyaController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'ini adalah menu untuk detail pintasan lainnya',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 45,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'kategori-media',
                'controller_name' => 'AdminWeb\\MediaDinamis\\MediaDinamisController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'ini adalah menu untuk mengatur kategori media',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 46,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'detail-media',
                'controller_name' => 'AdminWeb\\MediaDinamis\\DetailMediaDinamisController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'ini adalah menu untuk mengatur detail media',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 47,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'management-user',
                'controller_name' => 'ManagePengguna\\UserController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'ini adalah menu untuk melihat user yang ada ',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 48,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'daftar-verifikasi-pengajuan',
                'controller_name' => 'SistemInformasi\\DaftarPengajuan\\VerifPengajuan\\VerifPengajuanController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'ini adalah daftar verifikasi pengajuan',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 49,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'daftar-review-pengajuan',
                'controller_name' => 'SistemInformasi\\DaftarPengajuan\\ReviewPengajuan\\ReviewPengajuanController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'ini adalah daftar Review pengajuan',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 50,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'management-menu-url',
                'controller_name' => 'AdminWeb\\MenuManagement\\WebMenuUrlController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'ini adalah pengaturan untuk menu url',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 52,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'management-menu-global',
                'controller_name' => 'AdminWeb\\MenuManagement\\WebMenuGlobalController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'ini adalah pengaturan menu global untuk sistem ppid',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 53,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'whatsapp-management',
                'controller_name' => 'WhatsAppController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'menu untuk mengatur whatsapp management',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 55,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'kategori-informasi-publik-dinamis-tabel',
                'controller_name' => 'AdminWeb\\InformasiPublik\\TabelDinamis\\IpDinamisTabelController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'ini adalah pengaturan menu untuk kategori Informasi Publik yang berisi tabel dinamis',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 56,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'set-informasi-publik-dinamis-tabel',
                'controller_name' => 'AdminWeb\\InformasiPublik\\TabelDinamis\\SetIpDinamisTabelController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'ini adalah pengaturan menu untuk informasi dinamis tabel',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 57,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'get-informasi-publik-informasi-berkala',
                'controller_name' => 'AdminWeb\\InformasiPublik\\TabelDinamis\\GetIPInformasiBerkalaController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'menu untuk melihat seluruh data informasi publik dinamis tabel untuk sub menu Informasi Berkala',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 58,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'get-informasi-publik-informasi-serta-merta',
                'controller_name' => 'AdminWeb\\InformasiPublik\\TabelDinamis\\GetIPInformasiSertaMertaController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'menu untuk melihat seluruh data informasi publik dinamis tabel untuk sub menu Informasi Serta Merta',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 59,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'get-informasi-publik-informasi-setiap-saat',
                'controller_name' => 'AdminWeb\\InformasiPublik\\TabelDinamis\\GetIPInformasiSetiapSaatController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'menu untuk melihat seluruh data informasi publik dinamis tabel untuk sub menu Informasi Setiap Saat',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 60,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'notifikasi-masuk',
                'controller_name' => 'Notifikasi\\NotifMasukController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'Menu untuk menampilkan notifikasi pengajuan masuk',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 61,
                'fk_m_application' => 1,
                'wmu_parent_id' => null,
                'wmu_nama' => 'notifikasi-verifikasi',
                'controller_name' => 'Notifikasi\\NotifVerifController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'Menu untuk menampilkan notifikasi verifikasi pengajuan',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 62,
                'fk_m_application' => 1,
                'wmu_parent_id' => 48,
                'wmu_nama' => 'daftar-verifikasi-pengajuan-permohonan-informasi',
                'controller_name' => 'SistemInformasi\\DaftarPengajuan\\VerifPengajuan\\VerifPIController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'Daftar Verifikasi Pengajuan Permohonan Informasi',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 63,
                'fk_m_application' => 1,
                'wmu_parent_id' => 48,
                'wmu_nama' => 'daftar-verifikasi-pengajuan-pernyataan-keberatan',
                'controller_name' => 'SistemInformasi\\DaftarPengajuan\\VerifPengajuan\\VerifPKController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'Daftar Verifikasi Pengajuan Pernyataan Keberatan',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 64,
                'fk_m_application' => 1,
                'wmu_parent_id' => 48,
                'wmu_nama' => 'daftar-verifikasi-pengajuan-pengaduan-masyarakat',
                'controller_name' => 'SistemInformasi\\DaftarPengajuan\\VerifPengajuan\\VerifPMController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'Daftar Verifikasi Pengajuan Pengaduan Masyarakat',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 65,
                'fk_m_application' => 1,
                'wmu_parent_id' => 48,
                'wmu_nama' => 'daftar-verifikasi-pengajuan-whistle-blowing-system',
                'controller_name' => 'SistemInformasi\\DaftarPengajuan\\VerifPengajuan\\VerifWBSController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'Daftar Verifikasi Pengajuan Whistle Blowing System',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 66,
                'fk_m_application' => 1,
                'wmu_parent_id' => 48,
                'wmu_nama' => 'daftar-verifikasi-pengajuan-permohonan-perawatan',
                'controller_name' => 'SistemInformasi\\DaftarPengajuan\\VerifPengajuan\\VerifPPController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'Daftar Verifikasi Pengajuan Permohonan Perawatan Sarana Prasarana',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 67,
                'fk_m_application' => 1,
                'wmu_parent_id' => 49,
                'wmu_nama' => 'daftar-review-pengajuan-permohonan-informasi',
                'controller_name' => 'SistemInformasi\\DaftarPengajuan\\ReviewPengajuan\\ReviewPIController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'Daftar Review Pengajuan Permohonan Informasi',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 68,
                'fk_m_application' => 1,
                'wmu_parent_id' => 49,
                'wmu_nama' => 'daftar-review-pengajuan-pernyataan-keberatan',
                'controller_name' => 'SistemInformasi\\DaftarPengajuan\\ReviewPengajuan\\ReviewPKController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'Daftar Review Pengajuan Pernyataan Keberatan',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 69,
                'fk_m_application' => 1,
                'wmu_parent_id' => 49,
                'wmu_nama' => 'daftar-review-pengajuan-pengaduan-masyarakat',
                'controller_name' => 'SistemInformasi\\DaftarPengajuan\\ReviewPengajuan\\ReviewPMController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'Daftar Review Pengajuan Pengaduan Masyarakat',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 70,
                'fk_m_application' => 1,
                'wmu_parent_id' => 49,
                'wmu_nama' => 'daftar-review-pengajuan-whistle-blowing-system',
                'controller_name' => 'SistemInformasi\\DaftarPengajuan\\ReviewPengajuan\\ReviewWBSController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'Daftar Review Pengajuan Whistle Blowing System',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_url_id' => 71,
                'fk_m_application' => 1,
                'wmu_parent_id' => 49,
                'wmu_nama' => 'daftar-review-pengajuan-permohonan-perawatan',
                'controller_name' => 'SistemInformasi\\DaftarPengajuan\\ReviewPengajuan\\ReviewPPController',
                'module_type' => 'sisfo',
                'wmu_keterangan' => 'Daftar Review Pengajuan Permohonan Perawatan Sarana Prasarana',
                'wmu_kategori_menu' => 'custom',
                'wmu_akses_tabel' => null,
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
        ];

        DB::table('web_menu_url')->insertOrIgnore($data);
    }
}
