<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class Seeder000004WebMenuGlobal extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $data = [
            [
                'web_menu_global_id' => 1,
                'fk_web_menu_url' => null,
                'wmg_parent_id' => null,
                'wmg_icon' => 'fa-user-cog',
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Group Menu',
                'wmg_urutan_menu' => 1,
                'wmg_nama_default' => 'Management Pengguna',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 2,
                'fk_web_menu_url' => 1,
                'wmg_parent_id' => 1,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 1,
                'wmg_nama_default' => 'Menu Management',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 3,
                'fk_web_menu_url' => 2,
                'wmg_parent_id' => 1,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 2,
                'wmg_nama_default' => 'Management Level',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 4,
                'fk_web_menu_url' => 3,
                'wmg_parent_id' => null,
                'wmg_icon' => 'fa-home',
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Menu Biasa',
                'wmg_urutan_menu' => 2,
                'wmg_nama_default' => 'Beranda',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 5,
                'fk_web_menu_url' => null,
                'wmg_parent_id' => null,
                'wmg_icon' => 'fa-id-card',
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Group Menu',
                'wmg_urutan_menu' => 3,
                'wmg_nama_default' => 'Profile',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 6,
                'fk_web_menu_url' => 4,
                'wmg_parent_id' => 5,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 1,
                'wmg_nama_default' => 'Profil PPID',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 7,
                'fk_web_menu_url' => 5,
                'wmg_parent_id' => 5,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 2,
                'wmg_nama_default' => 'Profile Polinema',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 8,
                'fk_web_menu_url' => 6,
                'wmg_parent_id' => 5,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 3,
                'wmg_nama_default' => 'Struktur Organisasi',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 9,
                'fk_web_menu_url' => null,
                'wmg_parent_id' => null,
                'wmg_icon' => 'fa-wpforms',
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Group Menu',
                'wmg_urutan_menu' => 4,
                'wmg_nama_default' => 'E-Form',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 10,
                'fk_web_menu_url' => 7,
                'wmg_parent_id' => 9,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 1,
                'wmg_nama_default' => 'Permohonan Informasi',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 11,
                'fk_web_menu_url' => 8,
                'wmg_parent_id' => 9,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 2,
                'wmg_nama_default' => 'Pernyataan Keberatan',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 12,
                'fk_web_menu_url' => 9,
                'wmg_parent_id' => 9,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 3,
                'wmg_nama_default' => 'Pengaduan Masyarakat',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 13,
                'fk_web_menu_url' => 10,
                'wmg_parent_id' => 9,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 4,
                'wmg_nama_default' => 'Whistle Blowing System (WBS)',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 14,
                'fk_web_menu_url' => 11,
                'wmg_parent_id' => 9,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 5,
                'wmg_nama_default' => 'Permohonan Sarana dan Prasarana',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 15,
                'fk_web_menu_url' => null,
                'wmg_parent_id' => null,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Group Menu',
                'wmg_urutan_menu' => 5,
                'wmg_nama_default' => 'Informasi Publik',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 16,
                'fk_web_menu_url' => 12,
                'wmg_parent_id' => 15,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 1,
                'wmg_nama_default' => 'Regulasi',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 17,
                'fk_web_menu_url' => 13,
                'wmg_parent_id' => 15,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 2,
                'wmg_nama_default' => 'Daftar Informasi Publik',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 18,
                'fk_web_menu_url' => 14,
                'wmg_parent_id' => 15,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 3,
                'wmg_nama_default' => 'Informasi Berkala',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 19,
                'fk_web_menu_url' => 15,
                'wmg_parent_id' => 15,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 4,
                'wmg_nama_default' => 'Informasi Setiap Saat',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 20,
                'fk_web_menu_url' => 16,
                'wmg_parent_id' => 15,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 5,
                'wmg_nama_default' => 'Informasi Serta Merta',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 21,
                'fk_web_menu_url' => 17,
                'wmg_parent_id' => 15,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 6,
                'wmg_nama_default' => 'Informasi Dikecualikan',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 22,
                'fk_web_menu_url' => 18,
                'wmg_parent_id' => 15,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 7,
                'wmg_nama_default' => 'Laporan Harta Kekayaan Penyelenggara Negara (LHKPN)',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 23,
                'fk_web_menu_url' => null,
                'wmg_parent_id' => null,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Group Menu',
                'wmg_urutan_menu' => 6,
                'wmg_nama_default' => 'Layanan Informasi',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 24,
                'fk_web_menu_url' => 19,
                'wmg_parent_id' => 23,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 1,
                'wmg_nama_default' => 'Pedoman Umum Pengelolaan Layanan',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 25,
                'fk_web_menu_url' => 20,
                'wmg_parent_id' => 23,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 2,
                'wmg_nama_default' => 'Pedoman Layanan Kerjasama',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 26,
                'fk_web_menu_url' => 21,
                'wmg_parent_id' => 23,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 3,
                'wmg_nama_default' => 'Prosedur Layanan Informasi',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 27,
                'fk_web_menu_url' => null,
                'wmg_parent_id' => null,
                'wmg_icon' => 'fa-question-circle',
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Group Menu',
                'wmg_urutan_menu' => 7,
                'wmg_nama_default' => 'Management Form',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 28,
                'fk_web_menu_url' => 22,
                'wmg_parent_id' => 27,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 1,
                'wmg_nama_default' => 'Kategori Form',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 29,
                'fk_web_menu_url' => 23,
                'wmg_parent_id' => 27,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 2,
                'wmg_nama_default' => 'Timeline',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 30,
                'fk_web_menu_url' => 24,
                'wmg_parent_id' => 27,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 3,
                'wmg_nama_default' => 'Ketentuan Pelaporan',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 31,
                'fk_web_menu_url' => null,
                'wmg_parent_id' => null,
                'wmg_icon' => 'fa-columns',
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Group Menu',
                'wmg_urutan_menu' => 8,
                'wmg_nama_default' => 'Management Footer',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 32,
                'fk_web_menu_url' => 25,
                'wmg_parent_id' => 31,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 1,
                'wmg_nama_default' => 'Kategori Footer',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 33,
                'fk_web_menu_url' => 26,
                'wmg_parent_id' => 31,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 2,
                'wmg_nama_default' => 'Detail Footer',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 34,
                'fk_web_menu_url' => null,
                'wmg_parent_id' => null,
                'wmg_icon' => 'fa-bolt',
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Group Menu',
                'wmg_urutan_menu' => 9,
                'wmg_nama_default' => 'Management Akses & Pintasan Cepat',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 35,
                'fk_web_menu_url' => 27,
                'wmg_parent_id' => 34,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 1,
                'wmg_nama_default' => 'Kategori Akses Cepat',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 36,
                'fk_web_menu_url' => 28,
                'wmg_parent_id' => 34,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 2,
                'wmg_nama_default' => 'Detail Akses Cepat',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 37,
                'fk_web_menu_url' => 29,
                'wmg_parent_id' => 34,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 3,
                'wmg_nama_default' => 'Pintasan Lainnya',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 38,
                'fk_web_menu_url' => null,
                'wmg_parent_id' => null,
                'wmg_icon' => 'fa-newspaper',
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Group Menu',
                'wmg_urutan_menu' => 10,
                'wmg_nama_default' => 'Management Berita',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 39,
                'fk_web_menu_url' => 30,
                'wmg_parent_id' => 38,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 1,
                'wmg_nama_default' => 'Kategori Berita',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 40,
                'fk_web_menu_url' => 31,
                'wmg_parent_id' => 38,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 2,
                'wmg_nama_default' => 'Detail Berita',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 41,
                'fk_web_menu_url' => null,
                'wmg_parent_id' => null,
                'wmg_icon' => 'fa-bullhorn',
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Group Menu',
                'wmg_urutan_menu' => 11,
                'wmg_nama_default' => 'Management Pengumuman',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 42,
                'fk_web_menu_url' => 32,
                'wmg_parent_id' => 41,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 1,
                'wmg_nama_default' => 'Kategori Pengumuman',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 43,
                'fk_web_menu_url' => 33,
                'wmg_parent_id' => 41,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 2,
                'wmg_nama_default' => 'Detail Pengumuman',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 44,
                'fk_web_menu_url' => null,
                'wmg_parent_id' => null,
                'wmg_icon' => 'fa-file-alt',
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Group Menu',
                'wmg_urutan_menu' => 12,
                'wmg_nama_default' => 'Management LHKPN',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 45,
                'fk_web_menu_url' => 34,
                'wmg_parent_id' => 44,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 1,
                'wmg_nama_default' => 'Kategori Tahun LHKPN',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 46,
                'fk_web_menu_url' => 35,
                'wmg_parent_id' => 44,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 2,
                'wmg_nama_default' => 'Detail LHKPN',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 47,
                'fk_web_menu_url' => null,
                'wmg_parent_id' => null,
                'wmg_icon' => 'fa-gavel',
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Group Menu',
                'wmg_urutan_menu' => 13,
                'wmg_nama_default' => 'Management Regulasi',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 48,
                'fk_web_menu_url' => 36,
                'wmg_parent_id' => 47,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 1,
                'wmg_nama_default' => 'Kategori Regulasi',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 49,
                'fk_web_menu_url' => 37,
                'wmg_parent_id' => 47,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 2,
                'wmg_nama_default' => 'Regulasi Dinamis',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 50,
                'fk_web_menu_url' => 38,
                'wmg_parent_id' => 47,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 3,
                'wmg_nama_default' => 'Detail Regulasi',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 51,
                'fk_web_menu_url' => null,
                'wmg_parent_id' => null,
                'wmg_icon' => 'fa-folder-open',
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Group Menu',
                'wmg_urutan_menu' => 14,
                'wmg_nama_default' => 'E-Form Admin',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 52,
                'fk_web_menu_url' => 39,
                'wmg_parent_id' => 51,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 1,
                'wmg_nama_default' => 'Permohonan Informasi Admin',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 53,
                'fk_web_menu_url' => 40,
                'wmg_parent_id' => 51,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 2,
                'wmg_nama_default' => 'Pernyataan Keberatan Admin',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 54,
                'fk_web_menu_url' => 41,
                'wmg_parent_id' => 51,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 3,
                'wmg_nama_default' => 'Pengaduan Masyarakat Admin',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 55,
                'fk_web_menu_url' => 42,
                'wmg_parent_id' => 51,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 4,
                'wmg_nama_default' => 'Whistle Blowing System (WBS) Admin',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 56,
                'fk_web_menu_url' => 43,
                'wmg_parent_id' => 51,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 5,
                'wmg_nama_default' => 'Permohonan Sarana dan Prasarana Admin',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 57,
                'fk_web_menu_url' => 44,
                'wmg_parent_id' => 34,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 4,
                'wmg_nama_default' => 'Detail Pintasan Lainnya',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 58,
                'fk_web_menu_url' => null,
                'wmg_parent_id' => null,
                'wmg_icon' => 'fa-photo-video',
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Group Menu',
                'wmg_urutan_menu' => 15,
                'wmg_nama_default' => 'Management Media',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 59,
                'fk_web_menu_url' => 45,
                'wmg_parent_id' => 58,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 1,
                'wmg_nama_default' => 'Kategori Media',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
            [
                'web_menu_global_id' => 60,
                'fk_web_menu_url' => 46,
                'wmg_parent_id' => 58,
                'wmg_icon' => null,
                'wmg_type' => 'general',
                'wmg_kategori_menu' => 'Sub Menu',
                'wmg_urutan_menu' => 2,
                'wmg_nama_default' => 'Detail Media',
                'wmg_badge_method' => null,
                'wmg_status_menu' => 'aktif',
                'isDeleted' => 0,
                'created_by' => 'System',
                'created_at' => $now,
                'updated_by' => null,
                'updated_at' => null,
                'deleted_by' => null,
                'deleted_at' => null,
            ],
        ];

        DB::table('web_menu_global')->insertOrIgnore($data);
    }
}
